- name: Ensure directories exists
  ansible.builtin.file:
    dest: "{{ item }}"
    state: directory
    mode: '755'
  loop:
    - /opt/redis/

- name: Ensure docker-compose file has been updated
  ansible.builtin.template:
    src: "{{ item }}"
    dest: /opt/redis/
    mode: '644'
  loop:
    - docker-compose.yml

- name: Redis compose up
  community.docker.docker_compose:
    state: present
    project_src: /opt/redis/
    files:
      - docker-compose.yml
