- name: Download file from a file path
  ansible.builtin.get_url:
    url: https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh
    dest: /tmp/script.deb.sh
    mode: '555'

- name: Add the GitLab package repository
  ansible.builtin.command: "bash /tmp/script.deb.sh"
  changed_when: true

- name: Install packages
  ansible.builtin.apt:
    update_cache: true
    name:
      - gitlab-runner
    state: present

- name: Add gitlab-runner to docker group
  ansible.builtin.user:
    name: gitlab-runner
    groups: docker

- name: Ensure runner is started and enabled at boot
  ansible.builtin.systemd:
    name: gitlab-runner
    state: started
    enabled: true

# - name: Register gitlab shell runner
#   command: |
#     gitlab-runner register \
#     --non-interactive \
#     --url "https://gitlab.com/" \
#     --registration-token "{{ reg_token }}" \
#     --executor "shell" \
#     --description "shell executor" \
#     --tag-list "azure, shell, ansible" \
#     --run-untagged="false" \
#     --locked="true" \
#     --access-level="ref_protected"
