- name: Play for initializing server
  hosts: "main"
  vars_files:
    - "vars/main.yml"
  roles:
    - essentials
    - swap
    - docker
    - geerlingguy.docker
    - traefik
    - mysql
    - redis
    - node-exporter
    - gitlab
    - database-backup-storage
    - endlessh
    - reboot
