- name: Play for initializing server
  hosts: main
  roles:
    - essentials
    - swap
    - docker
    - traefik
    - mysql
    - redis
    - node-exporter
    - gitlab
    - database-backup-storage
    - tarpit
    - reboot
    
