- name: Disable password authentication
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#?PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present

- name: Set SSH port
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^Port"
    line: "Port {{ sshd_port }}"
    state: present

- name: Configure timezone
  community.general.timezone:
    name: "{{ timezone }}"

- name: Include package tasks
  ansible.builtin.include_tasks: packages.yml
