- name: Update and upgrade apt packages
  become: true
  ansible.builtin.apt:
    update_cache: true
    upgrade: full

- name: Install packages
  ansible.builtin.apt:
    name:
      - software-properties-common
      - apt-transport-https
      - build-essential
      - ca-certificates
      - smartmontools
      - python3-pip
      - lm-sensors
      - sysstat
      - iotop
      - iftop
      - htop
      - curl
      - git
    state: present
    update_cache: true
    allow_unauthenticated: true

- name: Update pip
  ansible.builtin.pip:
    name:
      - pip<=24.0
    state: present
  environment:
    PIP_BREAK_SYSTEM_PACKAGES: 1

- name: Install pip dependencies
  ansible.builtin.pip:
    name:
      - python-gitlab<=4.5.0
      - virtualenv
      - setuptools
  environment:
    PIP_BREAK_SYSTEM_PACKAGES: 1
